name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o server cmd/server/main.go

    - name: Test
      run: go test -v ./...

    - name: LS
      run: ls

    - name: SCP to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.ssh_private_key }}
        source: "server"
        target: "/home/go-simple-server/"

    - name: add env to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.ssh_private_key }}
        script: echo ${{ secrets.env }} >> /home/go-simple-server/.env

    - name: restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.serverKey }}
        script:
          systemctl restart simple-server.service &&
          systemctl status simple-server
    
